### ISSUE TITLE
ModuleNotFoundError: No module named 'pylab'

### ISSUE THREAD

**Issue by frutiemax92** [MCG-NJU/DDT#3]
On Ubuntu, when I follow the instructions for inference, I'm getting `ModuleNotFoundError: No module named 'pylab' `error.

**Comment by WANGSSSSSSS** [comment]
Since I used an internal docker image, there might still be other dependency missing issues. Could you please try again?

**Comment by WANGSSSSSSS** [comment]
The gradio demo are provided in `app.py`, directly run
```bash
python3 app.py
```

**Comment by WANGSSSSSSS** [comment]
> Since I used an internal docker image, there might still be other dependency missing issues. Could you please try again?

pull the latest commit and try again

**Comment by frutiemax92** [comment]
Packages I needed to install:

- torchvision
- soupsieve
- timm
- accelerate
- gradio

When I try to run the inference, I am getting stuck and it seems to require a dataloader, and loading in my 2 GPUs???
```
python main.py predict -c configs/repa_improved_ddt_xlen22de6_256.yaml --ckpt_path=model.ckpt
Seed set to 0
Using cache found in /home/lucas/.cache/torch/hub/facebookresearch_dinov2_main
current sampler is ODE sampler, but w_scheduler is enabled
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[rank: 1] Seed set to 0
Using cache found in /home/lucas/.cache/torch/hub/facebookresearch_dinov2_main
current sampler is ODE sampler, but w_scheduler is enabled
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.21.5+cuda12.4
Restoring states from the checkpoint path at model.ckpt
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Loaded model weights from the checkpoint at model.ckpt
Predicting: |                                                                                                                              | 0/? [00:00<?, ?it/s]Save images to universal_flow_workdirs/exp_repa_flatten_condit22_dit6_fixt_xl/val/predict
Predicting DataLoader 0:   0%| 
```
When I try to run the gradio app, I'm getting this:
```
python app.py
current sampler is ODE sampler, but w_scheduler is enabled
Traceback (most recent call last):
  File "/home/lucas/Documents/DDT/DDT/app.py", line 129, in <module>
    ckpt = torch.load(args.ckpt_path, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 1425, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 751, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 732, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models'
```

**Comment by WANGSSSSSSS** [comment]
> Packages I needed to install:
> 
> * torchvision
> * soupsieve
> * timm
> * accelerate
> * gradio
> 
> When I try to run the inference, I am getting stuck and it seems to require a dataloader, and loading in my 2 GPUs???
> 
> ```
> python main.py predict -c configs/repa_improved_ddt_xlen22de6_256.yaml --ckpt_path=model.ckpt
> Seed set to 0
> Using cache found in /home/lucas/.cache/torch/hub/facebookresearch_dinov2_main
> current sampler is ODE sampler, but w_scheduler is enabled
> Using bfloat16 Automatic Mixed Precision (AMP)
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> HPU available: False, using: 0 HPUs
> Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
> [rank: 1] Seed set to 0
> Using cache found in /home/lucas/.cache/torch/hub/facebookresearch_dinov2_main
> current sampler is ODE sampler, but w_scheduler is enabled
> Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
> ----------------------------------------------------------------------------------------------------
> distributed_backend=nccl
> All distributed processes registered. Starting with 2 processes
> ----------------------------------------------------------------------------------------------------
> 
> NCCL version 2.21.5+cuda12.4
> Restoring states from the checkpoint path at model.ckpt
> LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
> LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
> Loaded model weights from the checkpoint at model.ckpt
> Predicting: |                                                                                                                              | 0/? [00:00<?, ?it/s]Save images to universal_flow_workdirs/exp_repa_flatten_condit22_dit6_fixt_xl/val/predict
> Predicting DataLoader 0:   0%| 
> ```
> 
> When I try to run the gradio app, I'm getting this:
> 
> ```
> python app.py
> current sampler is ODE sampler, but w_scheduler is enabled
> Traceback (most recent call last):
>   File "/home/lucas/Documents/DDT/DDT/app.py", line 129, in <module>
>     ckpt = torch.load(args.ckpt_path, map_location="cpu")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 1425, in load
>     with _open_file_like(f, "rb") as opened_file:
>          ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 751, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lucas/Documents/DDT/DDT/.venv/lib/python3.12/site-packages/torch/serialization.py", line 732, in __init__
>     super().__init__(open(name, mode))
>                      ^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'models'
> ```

For the predict script, the progress bar actually infers 50K images with batch size 64 and ODE250 steps, which actually takes a lot of time. After finishing the whole progress bar, you will get raw images and an npz file. The NPS file can be directly used to evaluate the FID metrics with the ADM suite.

**Comment by WANGSSSSSSS** [comment]
By default, we infer 50K images with batch size 64. You can change the number of images and classes to infer with as :
```yaml
# in configs/repa_improved_ddt_xlen22de6_256.yaml
data:
  train_dataset: imagenet256
  train_root: /mnt/bn/wangshuai6/data/ImageNet/train
  train_image_size: 256
  train_batch_size: 16
  eval_max_num_instances: 50000
  pred_batch_size: 64
  # pred_batch_size: 16
  pred_num_workers: 4
  pred_seeds: null
  # pred_seeds: 1,2,3,4
  pred_selected_classes: null
  # pred_selected_classes:
  # - 0
  # - 1
  num_classes: 1000
  latent_shape:
  - 4
  - 32
  - 32
```
`pred_selected_classes` is a list of class indices to infer, if `pred_selected_classes` is null, all classes will be inferred.
`pred_seeds` is string of seeds for every class seprated with `,` to infer

**Comment by WANGSSSSSSS** [comment]
By default, the `main.py` will use all available GPUs. You can specify the GPU(s) to use with `CUDA_VISIBLE_DEVICES`.
or specify the number of GPUs to use with as :
```yaml
# in configs/repa_improved_ddt_xlen22de6_256.yaml
trainer:
  default_root_dir: universal_flow_workdirs
  accelerator: auto
  strategy: auto
  devices: auto
  # devices: 0,
  # devices: 0,1
  num_nodes: 1
```

**Comment by WANGSSSSSSS** [comment]
By default, the `save_image_callbacks` will only save the first 0 images and npz file(to calculate FID with ADM suite). You can change the number of images to save with as :  
```yaml
# in configs/repa_improved_ddt_xlen22de6_256.yaml
callbacks:
- class_path: src.callbacks.model_checkpoint.CheckpointHook
  init_args:
    every_n_train_steps: 10000
    save_top_k: -1
    save_last: true
- class_path: src.callbacks.save_images.SaveImagesHook
  init_args:
     save_dir: val
     max_save_num: 0
     # max_save_num: 100
```
